### ISSUE TITLE
twitter button obsolet

### ISSUE THREAD

**Issue by wuschLOR** [psyfako/psyfako-landing#3]
weil der konrat keine ahnung hat was twitter ist *seufts*

**Comment by NormanSurReal** [comment]
musst doch deswegen nicht den account löschen…

grüße by the way. kommst nach hamburg ?

**Comment by wuschLOR** [comment]
derpderp natürlich hab ich das nicht gemacht - ich weiß ja was twitter ist ...

**Comment by NormanSurReal** [comment]
und wer hat´s gemacht ?

und kommst du zur next Konferenz ?
